default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username:
  password:

development:
  <<: *default
  database: user_color_palette_development

test:
  <<: *default
  database: user_color_palette_test

production:
  <<: *default
  database: user_color_palette_prod
